version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'EST5EDT'
    networks:
      - dockprom_monitor_net
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - smb_data:/mnt:rw
    command: '-w "aurelien.maison" -s "Razor edge;/mnt;yes;no;no;aurelien;aurelien" -p'

networks:
  dockprom_monitor-net:
    external:

volumes:
  smb_data: {}
